### ISSUE TITLE
[Bug] Red stroke is not showing in default image on map.

### ISSUE THREAD

**Issue by Vishwajith-Shettigar** [Vishwajith-Shettigar/NextGen#75]
When nearby people shows on map with default image avatar, it doesn't show red border.

![Screenshot_2024-10-10-09-00-35-59](https://github.com/user-attachments/assets/d5c316dc-c464-4960-a375-5841218339a7)

**Comment by MiRa202321** [comment]
#75 I want to work on this bug. Can you please assign me this issue?

**Comment by MiRa202321** [comment]
I have made these changes in the fucntion **getRoundedBitmap()** in **NearByFragment class**. This will now create a circular bitmap with a red border around it instead of just a rounded bitmap.

![Screenshot 2024-10-11 103743](https://github.com/user-attachments/assets/5f6e534f-4bd8-445c-aff9-5ed5968fdfb5)



But while Rebuilding the Project I am encountering this error:


Execution failed for task ':data:kaptGenerateStubsDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 1.8) and 'kaptGenerateStubsDebugKotlin' task (current target is 17) jvm target compatibility should be set to the same Java version.
  Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 2m 46s
144 actionable tasks: 144 executed
The build scan was not published due to a configuration problem.
The Gradle Terms of Service have not been agreed to.
For more information, please see https://gradle.com/help/plugin-terms-of-service.
Alternatively, if you are using Gradle Enterprise, specify the server location.
For more information, please see https://gradle.com/help/plugin-enterprise-config.


To resolve this version incompatibility, I added this in app/build.gradle as well as data/build.gradle, but still it is not resolved,

//added these configurations to resolve Java version incompatibility error
            compileOptions {
                sourceCompatibility JavaVersion.VERSION_1_8
                targetCompatibility JavaVersion.VERSION_1_8
            }
            kotlinOptions {
                jvmTarget = '1.8'
            }

![Screenshot 2024-10-11 111638](https://github.com/user-attachments/assets/65cac838-207d-44de-bf56-d4bf628c804c)

**Comment by Vishwajith-Shettigar** [comment]
@MiRa202321, was your build successful before making any changes to the project?

**Comment by Vishwajith-Shettigar** [comment]
@MiRa202321, set your `JAVA_HOME` to JDK 17 in the environmental variables.

![Screenshot (156)](https://github.com/user-attachments/assets/e64e5d3a-a944-436d-a8a6-0af167d1f3a5)

**Comment by MiRa202321** [comment]
yes it was

**Comment by MiRa202321** [comment]
@Vishwajith-Shettigar It is resolved. Thank You..

**Comment by MiRa202321** [comment]
![Screenshot 2024-10-12 010249](https://github.com/user-attachments/assets/ddb5ac27-5de4-40c4-b03b-0ea7669a9f78)


@Vishwajith-Shettigar Why is the map blank? Can it be because of some fault while setting up? I have allowed the permissions to access my location.

**Comment by Vishwajith-Shettigar** [comment]
> ![Screenshot 2024-10-12 010249](https://private-user-images.githubusercontent.com/123196933/375869520-ddb5ac27-5de4-40c4-b03b-0ea7669a9f78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDY1OTEsIm5iZiI6MTcyODcwNjI5MSwicGF0aCI6Ii8xMjMxOTY5MzMvMzc1ODY5NTIwLWRkYjVhYzI3LTVkZTQtNDBjNC1iMDNiLTBlYTc2NjlhOWY3OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDExMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTQxMzVkZTRmNjY5YjI0YjFiMzM1MDdlNWRhY2U1NjFmODNlZGE4NWE0NzY3MjJkYTUxZDZjZTRiNzQ3NzAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7m029VsJaMIrm7443sq5_t2b0kD8t7wN-4hJvbBxpco)
> 
> @Vishwajith-Shettigar Why is the map blank? Can it be because of some fault while setting up? I have allowed the permissions to access my location.

I think you forgot to create Maps API key. Have a look at contributors guide.

**Comment by Vishwajith-Shettigar** [comment]
@MiRa202321 you can add below to troubleshooting guide.

https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2408345836

https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2406603579 ( Please have a quick chat with @MiRa202321 to understand the problem and solution she came up with.

https://github.com/Vishwajith-Shettigar/NextGen/discussions/47#discussion-7274929
